const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  SALES_MANAGER: 'SALES_MANAGER',
  SALES_EXECUTIVE: 'SALES_EXECUTIVE'
};

const USER_STATUS = {
  ACTIVE: 'ACTIVE',
  DEACTIVATED: 'DEACTIVATED'
};

const LEAD_STATUS = {
  NEW: 'NEW',
  CONTACTED: 'CONTACTED',
  IN_PROGRESS: 'IN_PROGRESS',
  CONVERTED: 'CONVERTED',
  LOST: 'LOST'
};

const REVENUE_STATUS = {
  PAID: 'PAID',
  PENDING: 'PENDING'
};

const PAYMENT_METHODS = {
  STRIPE: 'STRIPE',
  UPI: 'UPI',
  BANK_TRANSFER: 'BANK_TRANSFER',
  CASH: 'CASH',
  PENDING: 'PENDING'
};

const FILE_IMPORT_STATUS = {
  SUCCESS: 'SUCCESS',
  PARTIAL: 'PARTIAL',
  FAILED: 'FAILED'
};

module.exports = {
  ROLES,
  USER_STATUS,
  LEAD_STATUS,
  REVENUE_STATUS,
  PAYMENT_METHODS,
  FILE_IMPORT_STATUS
};
